spring.application.name=EmployeeManagementSystem

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_management_system_new}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.liquibase.enabled=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

